export interface ElementNode {
  number: number;
  symbol: string;
  name: string;
  xpos: number; // 1-18
  ypos: number; // 1-7 (9-10 for lanthanides/actinides)
  category: string;
  mass?: string;
  electronegativity?: number; // Pauling scale
  radius?: number; // pm
}

export const ELEMENTS: ElementNode[] = [
  // Row 1
  { number: 1, symbol: 'H', name: 'Hydrogen', xpos: 1, ypos: 1, category: 'reactive-nonmetal', mass: '1.008', electronegativity: 2.20, radius: 37 },
  { number: 2, symbol: 'He', name: 'Helium', xpos: 18, ypos: 1, category: 'noble-gas', mass: '4.0026', electronegativity: 0, radius: 31 },
  // Row 2
  { number: 3, symbol: 'Li', name: 'Lithium', xpos: 1, ypos: 2, category: 'alkali-metal', mass: '6.94', electronegativity: 0.98, radius: 152 },
  { number: 4, symbol: 'Be', name: 'Beryllium', xpos: 2, ypos: 2, category: 'alkaline-earth', mass: '9.0122', electronegativity: 1.57, radius: 112 },
  { number: 5, symbol: 'B', name: 'Boron', xpos: 13, ypos: 2, category: 'metalloid', mass: '10.81', electronegativity: 2.04, radius: 82 },
  { number: 6, symbol: 'C', name: 'Carbon', xpos: 14, ypos: 2, category: 'reactive-nonmetal', mass: '12.011', electronegativity: 2.55, radius: 77 },
  { number: 7, symbol: 'N', name: 'Nitrogen', xpos: 15, ypos: 2, category: 'reactive-nonmetal', mass: '14.007', electronegativity: 3.04, radius: 75 },
  { number: 8, symbol: 'O', name: 'Oxygen', xpos: 16, ypos: 2, category: 'reactive-nonmetal', mass: '15.999', electronegativity: 3.44, radius: 73 },
  { number: 9, symbol: 'F', name: 'Fluorine', xpos: 17, ypos: 2, category: 'reactive-nonmetal', mass: '18.998', electronegativity: 3.98, radius: 71 },
  { number: 10, symbol: 'Ne', name: 'Neon', xpos: 18, ypos: 2, category: 'noble-gas', mass: '20.180', electronegativity: 0, radius: 38 },
  // Row 3
  { number: 11, symbol: 'Na', name: 'Sodium', xpos: 1, ypos: 3, category: 'alkali-metal', mass: '22.990', electronegativity: 0.93, radius: 186 },
  { number: 12, symbol: 'Mg', name: 'Magnesium', xpos: 2, ypos: 3, category: 'alkaline-earth', mass: '24.305', electronegativity: 1.31, radius: 160 },
  { number: 13, symbol: 'Al', name: 'Aluminium', xpos: 13, ypos: 3, category: 'post-transition-metal', mass: '26.982', electronegativity: 1.61, radius: 143 },
  { number: 14, symbol: 'Si', name: 'Silicon', xpos: 14, ypos: 3, category: 'metalloid', mass: '28.085', electronegativity: 1.90, radius: 118 },
  { number: 15, symbol: 'P', name: 'Phosphorus', xpos: 15, ypos: 3, category: 'reactive-nonmetal', mass: '30.974', electronegativity: 2.19, radius: 110 },
  { number: 16, symbol: 'S', name: 'Sulfur', xpos: 16, ypos: 3, category: 'reactive-nonmetal', mass: '32.06', electronegativity: 2.58, radius: 102 },
  { number: 17, symbol: 'Cl', name: 'Chlorine', xpos: 17, ypos: 3, category: 'reactive-nonmetal', mass: '35.45', electronegativity: 3.16, radius: 99 },
  { number: 18, symbol: 'Ar', name: 'Argon', xpos: 18, ypos: 3, category: 'noble-gas', mass: '39.948', electronegativity: 0, radius: 71 },
  // Row 4
  { number: 19, symbol: 'K', name: 'Potassium', xpos: 1, ypos: 4, category: 'alkali-metal', mass: '39.098', electronegativity: 0.82, radius: 227 },
  { number: 20, symbol: 'Ca', name: 'Calcium', xpos: 2, ypos: 4, category: 'alkaline-earth', mass: '40.078', electronegativity: 1.00, radius: 197 },
  { number: 21, symbol: 'Sc', name: 'Scandium', xpos: 3, ypos: 4, category: 'transition-metal', mass: '44.956', electronegativity: 1.36, radius: 162 },
  { number: 22, symbol: 'Ti', name: 'Titanium', xpos: 4, ypos: 4, category: 'transition-metal', mass: '47.867', electronegativity: 1.54, radius: 147 },
  { number: 23, symbol: 'V', name: 'Vanadium', xpos: 5, ypos: 4, category: 'transition-metal', mass: '50.942', electronegativity: 1.63, radius: 134 },
  { number: 24, symbol: 'Cr', name: 'Chromium', xpos: 6, ypos: 4, category: 'transition-metal', mass: '51.996', electronegativity: 1.66, radius: 128 },
  { number: 25, symbol: 'Mn', name: 'Manganese', xpos: 7, ypos: 4, category: 'transition-metal', mass: '54.938', electronegativity: 1.55, radius: 127 },
  { number: 26, symbol: 'Fe', name: 'Iron', xpos: 8, ypos: 4, category: 'transition-metal', mass: '55.845', electronegativity: 1.83, radius: 126 },
  { number: 27, symbol: 'Co', name: 'Cobalt', xpos: 9, ypos: 4, category: 'transition-metal', mass: '58.933', electronegativity: 1.88, radius: 125 },
  { number: 28, symbol: 'Ni', name: 'Nickel', xpos: 10, ypos: 4, category: 'transition-metal', mass: '58.693', electronegativity: 1.91, radius: 124 },
  { number: 29, symbol: 'Cu', name: 'Copper', xpos: 11, ypos: 4, category: 'transition-metal', mass: '63.546', electronegativity: 1.90, radius: 128 },
  { number: 30, symbol: 'Zn', name: 'Zinc', xpos: 12, ypos: 4, category: 'transition-metal', mass: '65.38', electronegativity: 1.65, radius: 134 },
  { number: 31, symbol: 'Ga', name: 'Gallium', xpos: 13, ypos: 4, category: 'post-transition-metal', mass: '69.723', electronegativity: 1.81, radius: 135 },
  { number: 32, symbol: 'Ge', name: 'Germanium', xpos: 14, ypos: 4, category: 'metalloid', mass: '72.63', electronegativity: 2.01, radius: 122 },
  { number: 33, symbol: 'As', name: 'Arsenic', xpos: 15, ypos: 4, category: 'metalloid', mass: '74.922', electronegativity: 2.18, radius: 119 },
  { number: 34, symbol: 'Se', name: 'Selenium', xpos: 16, ypos: 4, category: 'reactive-nonmetal', mass: '78.971', electronegativity: 2.55, radius: 116 },
  { number: 35, symbol: 'Br', name: 'Bromine', xpos: 17, ypos: 4, category: 'reactive-nonmetal', mass: '79.904', electronegativity: 2.96, radius: 114 },
  { number: 36, symbol: 'Kr', name: 'Krypton', xpos: 18, ypos: 4, category: 'noble-gas', mass: '83.798', electronegativity: 3.00, radius: 110 },
  // Row 5
  { number: 37, symbol: 'Rb', name: 'Rubidium', xpos: 1, ypos: 5, category: 'alkali-metal', mass: '85.468', electronegativity: 0.82, radius: 248 },
  { number: 38, symbol: 'Sr', name: 'Strontium', xpos: 2, ypos: 5, category: 'alkaline-earth', mass: '87.62', electronegativity: 0.95, radius: 215 },
  { number: 39, symbol: 'Y', name: 'Yttrium', xpos: 3, ypos: 5, category: 'transition-metal', mass: '88.906', electronegativity: 1.22, radius: 180 },
  { number: 40, symbol: 'Zr', name: 'Zirconium', xpos: 4, ypos: 5, category: 'transition-metal', mass: '91.224', electronegativity: 1.33, radius: 160 },
  { number: 41, symbol: 'Nb', name: 'Niobium', xpos: 5, ypos: 5, category: 'transition-metal', mass: '92.906', electronegativity: 1.6, radius: 146 },
  { number: 42, symbol: 'Mo', name: 'Molybdenum', xpos: 6, ypos: 5, category: 'transition-metal', mass: '95.95', electronegativity: 2.16, radius: 139 },
  { number: 43, symbol: 'Tc', name: 'Technetium', xpos: 7, ypos: 5, category: 'transition-metal', mass: '98', electronegativity: 1.9, radius: 136 },
  { number: 44, symbol: 'Ru', name: 'Ruthenium', xpos: 8, ypos: 5, category: 'transition-metal', mass: '101.07', electronegativity: 2.2, radius: 134 },
  { number: 45, symbol: 'Rh', name: 'Rhodium', xpos: 9, ypos: 5, category: 'transition-metal', mass: '102.91', electronegativity: 2.28, radius: 134 },
  { number: 46, symbol: 'Pd', name: 'Palladium', xpos: 10, ypos: 5, category: 'transition-metal', mass: '106.42', electronegativity: 2.20, radius: 137 },
  { number: 47, symbol: 'Ag', name: 'Silver', xpos: 11, ypos: 5, category: 'transition-metal', mass: '107.87', electronegativity: 1.93, radius: 144 },
  { number: 48, symbol: 'Cd', name: 'Cadmium', xpos: 12, ypos: 5, category: 'transition-metal', mass: '112.41', electronegativity: 1.69, radius: 151 },
  { number: 49, symbol: 'In', name: 'Indium', xpos: 13, ypos: 5, category: 'post-transition-metal', mass: '114.82', electronegativity: 1.78, radius: 167 },
  { number: 50, symbol: 'Sn', name: 'Tin', xpos: 14, ypos: 5, category: 'post-transition-metal', mass: '118.71', electronegativity: 1.96, radius: 140 },
  { number: 51, symbol: 'Sb', name: 'Antimony', xpos: 15, ypos: 5, category: 'metalloid', mass: '121.76', electronegativity: 2.05, radius: 140 },
  { number: 52, symbol: 'Te', name: 'Tellurium', xpos: 16, ypos: 5, category: 'metalloid', mass: '127.60', electronegativity: 2.1, radius: 142 },
  { number: 53, symbol: 'I', name: 'Iodine', xpos: 17, ypos: 5, category: 'reactive-nonmetal', mass: '126.90', electronegativity: 2.66, radius: 133 },
  { number: 54, symbol: 'Xe', name: 'Xenon', xpos: 18, ypos: 5, category: 'noble-gas', mass: '131.29', electronegativity: 2.6, radius: 131 },
  // Row 6
  { number: 55, symbol: 'Cs', name: 'Caesium', xpos: 1, ypos: 6, category: 'alkali-metal' },
  { number: 56, symbol: 'Ba', name: 'Barium', xpos: 2, ypos: 6, category: 'alkaline-earth' },
  { number: 57, symbol: 'La', name: 'Lanthanum', xpos: 3, ypos: 6, category: 'transition-metal' },
  { number: 72, symbol: 'Hf', name: 'Hafnium', xpos: 4, ypos: 6, category: 'transition-metal' },
  { number: 73, symbol: 'Ta', name: 'Tantalum', xpos: 5, ypos: 6, category: 'transition-metal' },
  { number: 74, symbol: 'W', name: 'Tungsten', xpos: 6, ypos: 6, category: 'transition-metal' },
  { number: 75, symbol: 'Re', name: 'Rhenium', xpos: 7, ypos: 6, category: 'transition-metal' },
  { number: 76, symbol: 'Os', name: 'Osmium', xpos: 8, ypos: 6, category: 'transition-metal' },
  { number: 77, symbol: 'Ir', name: 'Iridium', xpos: 9, ypos: 6, category: 'transition-metal' },
  { number: 78, symbol: 'Pt', name: 'Platinum', xpos: 10, ypos: 6, category: 'transition-metal' },
  { number: 79, symbol: 'Au', name: 'Gold', xpos: 11, ypos: 6, category: 'transition-metal' },
  { number: 80, symbol: 'Hg', name: 'Mercury', xpos: 12, ypos: 6, category: 'transition-metal' },
  { number: 81, symbol: 'Tl', name: 'Thallium', xpos: 13, ypos: 6, category: 'post-transition-metal' },
  { number: 82, symbol: 'Pb', name: 'Lead', xpos: 14, ypos: 6, category: 'post-transition-metal' },
  { number: 83, symbol: 'Bi', name: 'Bismuth', xpos: 15, ypos: 6, category: 'post-transition-metal' },
  { number: 84, symbol: 'Po', name: 'Polonium', xpos: 16, ypos: 6, category: 'post-transition-metal' },
  { number: 85, symbol: 'At', name: 'Astatine', xpos: 17, ypos: 6, category: 'post-transition-metal' },
  { number: 86, symbol: 'Rn', name: 'Radon', xpos: 18, ypos: 6, category: 'noble-gas' },
  // Row 7
  { number: 87, symbol: 'Fr', name: 'Francium', xpos: 1, ypos: 7, category: 'alkali-metal' },
  { number: 88, symbol: 'Ra', name: 'Radium', xpos: 2, ypos: 7, category: 'alkaline-earth' },
  { number: 89, symbol: 'Ac', name: 'Actinium', xpos: 3, ypos: 7, category: 'transition-metal' },
  { number: 104, symbol: 'Rf', name: 'Rutherfordium', xpos: 4, ypos: 7, category: 'transition-metal' },
  { number: 105, symbol: 'Db', name: 'Dubnium', xpos: 5, ypos: 7, category: 'transition-metal' },
  { number: 106, symbol: 'Sg', name: 'Seaborgium', xpos: 6, ypos: 7, category: 'transition-metal' },
  { number: 107, symbol: 'Bh', name: 'Bohrium', xpos: 7, ypos: 7, category: 'transition-metal' },
  { number: 108, symbol: 'Hs', name: 'Hassium', xpos: 8, ypos: 7, category: 'transition-metal' },
  { number: 109, symbol: 'Mt', name: 'Meitnerium', xpos: 9, ypos: 7, category: 'transition-metal' },
  { number: 110, symbol: 'Ds', name: 'Darmstadtium', xpos: 10, ypos: 7, category: 'transition-metal' },
  { number: 111, symbol: 'Rg', name: 'Roentgenium', xpos: 11, ypos: 7, category: 'transition-metal' },
  { number: 112, symbol: 'Cn', name: 'Copernicium', xpos: 12, ypos: 7, category: 'transition-metal' },
  { number: 113, symbol: 'Nh', name: 'Nihonium', xpos: 13, ypos: 7, category: 'post-transition-metal' },
  { number: 114, symbol: 'Fl', name: 'Flerovium', xpos: 14, ypos: 7, category: 'post-transition-metal' },
  { number: 115, symbol: 'Mc', name: 'Moscovium', xpos: 15, ypos: 7, category: 'post-transition-metal' },
  { number: 116, symbol: 'Lv', name: 'Livermorium', xpos: 16, ypos: 7, category: 'post-transition-metal' },
  { number: 117, symbol: 'Ts', name: 'Tennessine', xpos: 17, ypos: 7, category: 'post-transition-metal' },
  { number: 118, symbol: 'Og', name: 'Oganesson', xpos: 18, ypos: 7, category: 'noble-gas' },
  // Bottom Block - Lanthanides (ypos 9)
  { number: 58, symbol: 'Ce', name: 'Cerium', xpos: 4, ypos: 9, category: 'lanthanide' },
  { number: 59, symbol: 'Pr', name: 'Praseodymium', xpos: 5, ypos: 9, category: 'lanthanide' },
  { number: 60, symbol: 'Nd', name: 'Neodymium', xpos: 6, ypos: 9, category: 'lanthanide' },
  { number: 61, symbol: 'Pm', name: 'Promethium', xpos: 7, ypos: 9, category: 'lanthanide' },
  { number: 62, symbol: 'Sm', name: 'Samarium', xpos: 8, ypos: 9, category: 'lanthanide' },
  { number: 63, symbol: 'Eu', name: 'Europium', xpos: 9, ypos: 9, category: 'lanthanide' },
  { number: 64, symbol: 'Gd', name: 'Gadolinium', xpos: 10, ypos: 9, category: 'lanthanide' },
  { number: 65, symbol: 'Tb', name: 'Terbium', xpos: 11, ypos: 9, category: 'lanthanide' },
  { number: 66, symbol: 'Dy', name: 'Dysprosium', xpos: 12, ypos: 9, category: 'lanthanide' },
  { number: 67, symbol: 'Ho', name: 'Holmium', xpos: 13, ypos: 9, category: 'lanthanide' },
  { number: 68, symbol: 'Er', name: 'Erbium', xpos: 14, ypos: 9, category: 'lanthanide' },
  { number: 69, symbol: 'Tm', name: 'Thulium', xpos: 15, ypos: 9, category: 'lanthanide' },
  { number: 70, symbol: 'Yb', name: 'Ytterbium', xpos: 16, ypos: 9, category: 'lanthanide' },
  { number: 71, symbol: 'Lu', name: 'Lutetium', xpos: 17, ypos: 9, category: 'lanthanide' },
  // Bottom Block - Actinides (ypos 10)
  { number: 90, symbol: 'Th', name: 'Thorium', xpos: 4, ypos: 10, category: 'actinide' },
  { number: 91, symbol: 'Pa', name: 'Protactinium', xpos: 5, ypos: 10, category: 'actinide' },
  { number: 92, symbol: 'U', name: 'Uranium', xpos: 6, ypos: 10, category: 'actinide' },
  { number: 93, symbol: 'Np', name: 'Neptunium', xpos: 7, ypos: 10, category: 'actinide' },
  { number: 94, symbol: 'Pu', name: 'Plutonium', xpos: 8, ypos: 10, category: 'actinide' },
  { number: 95, symbol: 'Am', name: 'Americium', xpos: 9, ypos: 10, category: 'actinide' },
  { number: 96, symbol: 'Cm', name: 'Curium', xpos: 10, ypos: 10, category: 'actinide' },
  { number: 97, symbol: 'Bk', name: 'Berkelium', xpos: 11, ypos: 10, category: 'actinide' },
  { number: 98, symbol: 'Cf', name: 'Californium', xpos: 12, ypos: 10, category: 'actinide' },
  { number: 99, symbol: 'Es', name: 'Einsteinium', xpos: 13, ypos: 10, category: 'actinide' },
  { number: 100, symbol: 'Fm', name: 'Fermium', xpos: 14, ypos: 10, category: 'actinide' },
  { number: 101, symbol: 'Md', name: 'Mendelevium', xpos: 15, ypos: 10, category: 'actinide' },
  { number: 102, symbol: 'No', name: 'Nobelium', xpos: 16, ypos: 10, category: 'actinide' },
  { number: 103, symbol: 'Lr', name: 'Lawrencium', xpos: 17, ypos: 10, category: 'actinide' },
];
